# Generated by Django 4.2.7 on 2026-01-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_profiles/'),
        ),
        migrations.CreateModel(
            name='DonationReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='donors.donationschedule')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='donors.donorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
