# Generated by Django 4.2.7 on 2026-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_profiles/'),
        ),
    ]
