# Generated by Django 4.2.7 on 2026-01-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(default='Blood Bank', max_length=150),
            preserve_default=False,
        ),
    ]
