# Generated by Django 4.2.7 on 2026-01-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0002_bloodbank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='bloodbank_profiles/'),
        ),
    ]
